# Development Profile Configuration
spring:
  config:
    activate:
      on-profile: development

  cloud:
    aws:
      region:
        static: us-east-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      stack:
        auto: false
      sqs:
        listener:
          acknowledgement-mode: on-success
          visibility-timeout: 300

# AWS Configuration for Development
aws:
  region: us-east-2
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:http://dynamodb-local:8000}
  access:
    key: ${AWS_ACCESS_KEY:test-key}
  secret:
    key: ${AWS_SECRET_KEY:test-secret}
  sqs:
    payment-request-queue: ${PAYMENT_REQUEST_QUEUE}
    payment-request-dlq: ${PAYMENT_REQUEST_DLQ}
    payment-response-success-queue: ${PAYMENT_RESPONSE_SUCCESS_QUEUE}
    payment-response-failure-queue: ${PAYMENT_RESPONSE_FAILURE_QUEUE}
    auto-create-queue: true
    max-receive-count: 3

# DynamoDB Configuration for Development
dynamodb:
  table-name: ${DYNAMODB_TABLE_NAME:payments-dev}

# Mercado Pago Configuration (dummy values for local development)
mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN}
  public-key: ${MERCADOPAGO_PUBLIC_KEY}

# Actuator Configuration for Development
management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.fiap.billing_service: DEBUG
    com.icegreen.greenmail: DEBUG
    org.springframework.mail: DEBUG
